#!/bin/sh

# Run relative to script location
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

usage() {
  echo "usage: $0 [-ahrx] [-c HTML_color] [-f format] [-t duration]"
  echo
  echo "  -a, --sort               Play videos alphabetically."
  echo "  -c, --color HTML_color   Tint video files. (Default: '3b1e00')"
  echo "  -f, --format format      Set playlist format {'m3u'|'xspf'}."
  echo "                           (Default: 'm3u')"
  echo "  -h, --help               Display this message."
  echo "  -r, --recursive          Include files in subfolders."
  echo "  -t, --time duration      Set duration of each video, in seconds."
  echo "                           (Default: '30')"
  echo "  -x, --no-effects         Remove all audio and video effects."
}

# Set defaults
playlist_format="m3u"
playlist_name="$(basename "$PWD")"
clip_duration_in_seconds=30
playlist_duration_in_hours=4
color_tint="3b1e00"
has_effects=true
is_alphabetical=false
is_recursive=false

# Process flags and override defaults
while [ "$1" != "" ]; do
  case $1 in
    -a | --sort)
      is_alphabetical=true
      ;;
    -c | --color)
      opt="$1"
      shift
      color_tint=$1
      if [[ ! "$color_tint" =~ ^([[:xdigit:]]{6})$ ]]
      then
        echo "error: Option '$opt' requires a 6-digit HTML color."
        usage
        exit 1
      fi
      ;;
    -f | --format)
      opt="$1"
      shift
      playlist_format=$1
      if [[ ! "$playlist_format" =~ ^(m3u|xspf)$ ]]
      then
        echo "error: Option '$opt' requires a playlist format {'m3u'|'xspf'}."
        usage
        exit 1
      fi
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    -r | --recursive)
      is_recursive=true
      ;;
    -t | --time)
      opt="$1"
      shift
      clip_duration_in_seconds=$1
      if [[ ! "$clip_duration_in_seconds" =~ ^([0-9]+)$ ]]
      then
        echo "error: Option '$opt' requires an integer duration."
        usage
        exit 1
      fi
      ;;
    -x | --no-effects)
      has_effects=false
      ;;
    *)
      echo "error: Unknown option or argument '$1'."
      usage
      exit 1
      ;;
  esac
  shift
done

echo "Generating playlist..."
python3 build_playlist.py $clip_duration_in_seconds $playlist_duration_in_hours "$playlist_name" $playlist_format $is_recursive $is_alphabetical
echo "Playing playlist..."

playlist_options="--playlist-autostart --fullscreen --no-osd --loop --no-random"
video_options=""
if $has_effects
then
  video_options="--no-audio --rate=0.67 --video-filter extract:adjust --extract-component=0x$color_tint --contrast=1.2 --brightness=1.05"
fi

/Applications/VLC.app/Contents/MacOS/VLC $playlist_options $video_options "$playlist_name.$playlist_format"
